# -*- coding: utf-8 -*-
"""build_index

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STHX-jqJqfQHjg7p5yO2fnPBdvLj0h4R
"""

from rag.loader import load_pdf
from rag.chunker import split_documents
from rag.embedder import get_embedding_model
from rag.retriever import create_vector_db

def run_pipeline():
    print("Loading data...")
    docs = load_pdf("data/data_sample.pdf")

    print("Chunking...")
    chunks = split_documents(docs)

    print("Embedding and Saving to Disk...")
    embed_model = get_embedding_model()
    create_vector_db(chunks, embed_model)
    print("Index built successfully!")

if __name__ == "__main__":
    run_pipeline()
