# -*- coding: utf-8 -*-
"""chunker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STHX-jqJqfQHjg7p5yO2fnPBdvLj0h4R
"""

from langchain_text_splitters import RecursiveCharacterTextSplitter

def split_documents(docs):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=100
    )
    return text_splitter.split_documents(docs)