# -*- coding: utf-8 -*-
"""embedder

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STHX-jqJqfQHjg7p5yO2fnPBdvLj0h4R
"""

from langchain_openai import OpenAIEmbeddings # Or HuggingFaceEmbeddings

def get_embedding_model():
    return OpenAIEmbeddings(model="text-embedding-3-small")