# -*- coding: utf-8 -*-
"""embedder

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STHX-jqJqfQHjg7p5yO2fnPBdvLj0h4R
"""

from langchain_community.vectorstores import Chroma

def create_vector_db(chunks, embedding_model, persist_directory="./db"):
    vectordb = Chroma.from_documents(
        documents=chunks,
        embedding=embedding_model,
        persist_directory=persist_directory
    )
    return vectordb.as_retriever(search_kwargs={"k": 3})